### ISSUE TITLE
动态添加菜单时，样式问题

### ISSUE THREAD

**Issue by xiongxin** [vusion/cloud-ui#53]
![Screenshot from 2019-09-16 11-44-00](https://user-images.githubusercontent.com/2803069/64933330-5200c200-d877-11e9-91ab-e5f70030b74a.png)

**Comment by xiongxin** [comment]
```
<u-linear-layout direction="vertical">
      <u-navbar>
        <div slot="left">
          <u-logo name="163yun" color="2color">用户名</u-logo>
        </div>
        <u-navbar-item to="/">首页</u-navbar-item>
        <u-navbar-item
                :key="item.name"
                v-for="item in options"
                :to="item.route">{{ item.name }}&nbsp;&nbsp;<span class="u-tabs_close" @click="close(item)"></span></u-navbar-item>
      </u-navbar>
    </u-linear-layout>
```

**Comment by rainfore** [comment]
Hi，你好，麻烦再详细说一下遇到的问题

**Comment by xiongxin** [comment]
> Hi，你好，麻烦再详细说一下遇到的问题。
> 是因为两个都高亮了是吗？
> 
> 加上 `exact`
> 
> ```
> <u-navbar-item to="/" exact>首页</u-navbar-item>
> ```

好的，是这个问题，不好意思没描述清楚

**Comment by rainfore** [comment]
Hi，请问您是哪边的朋友。后续有什么需要，我们可以即时联系。

**Comment by xiongxin** [comment]
我不是网易的，我就是一个普通的开发，用这个在做两个自己的项目，一个是web后台管理的应用，一个是electron应用， 因为我之前在网易微专业学过前端，对于网易的前端技术比较有感情，会经常关注，有好用的就用起来
